/*======================================================================
    xrot
========================================================================*/

#include "pixmap/titlem.xpm"
#include "pixmap/down.xpm"
#include "pixmap/left.xpm"
#include "pixmap/right.xpm"
#include "pixmap/up.xpm"
#include "pixmap/down1.xpm"
#include "pixmap/left1.xpm"
#include "pixmap/right1.xpm"
#include "pixmap/up1.xpm"
#include "pixmap/left2.xpm"
#include "pixmap/right2.xpm"
#include "pixmap/frame.xpm"
#include "pixmap/wall1.xpm"
#include "pixmap/wall2.xpm"
#include "pixmap/wall3.xpm"
#include "pixmap/wall4.xpm"
#include "pixmap/wall5.xpm"
#include "pixmap/wall6.xpm"
#include "pixmap/wall7.xpm"
#include "pixmap/wall8.xpm"
#include "pixmap/wall9.xpm"
#include "pixmap/wall10.xpm"
#include "pixmap/pin.xpm"
#include "pixmap/ball.xpm"
#include "pixmap/ball2.xpm"
#include "pixmap/ball3.xpm"
#include "pixmap/bg1.xpm"
#include "pixmap/bg2.xpm"
#include "pixmap/bg3.xpm"
#include "pixmap/bg4.xpm"
#include "pixmap/one.xpm"
#include "pixmap/two.xpm"
#include "pixmap/three.xpm"
#include "pixmap/go.xpm"
#include "pixmap/goal.xpm"
